# automatically generated by the FlatBuffers compiler, do not modify

# namespace: snapshot

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Snapshot(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Snapshot()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSnapshot(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Snapshot
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Snapshot
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Snapshot
    def Data(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def SnapshotStart(builder):
    builder.StartObject(2)

def Start(builder):
    SnapshotStart(builder)

def SnapshotAddId(builder, id):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)

def AddId(builder, id):
    SnapshotAddId(builder, id)

def SnapshotAddData(builder, data):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(data), 0)

def AddData(builder, data):
    SnapshotAddData(builder, data)

def SnapshotEnd(builder):
    return builder.EndObject()

def End(builder):
    return SnapshotEnd(builder)
